name: Cleanup

on:
  workflow_call:
    inputs:
      cluster-name:
        required: true
        description: AKS Cluster Name With Randomly Generated Suffix
        type: string
  workflow_dispatch:
    inputs:
      cluster-name:
        required: true
        description: AKS Cluster Name With Randomly Generated Suffix
        type: string


jobs:
  setup-workload-identity:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:

      - name: Log into Azure
        run: |
          az login --service-principal \
            --username ${{ secrets.AZURE_SERVICE_PRINCIPAL_APP_ID }} \
            --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} \
            --tenant ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}

      - name: Cleanup
        id: cleanup
        env: 
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }} 
          CLUSTER_NAME: ${{ inputs.cluster-name }}
        run: | 
          az aks stop --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME 2>&1
          sleep 30 
          az aks delete --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --no-wait --yes