name: Resolve Manifest Variables

on:
  workflow_call:
    inputs:
      manifest:
        required: true
        type: string
        description: The Path to the Manifest File
      modifiers:
        type: string
        required: false
        default: ""
        description: Semi colon separated key value pairs of environment variables to override
    outputs:
      manifest:
        description: The manifest whith values resolved
        value: ${{ jobs.resolve-manifest-variables.outputs.manifest }}

jobs:
  resolve-manifest-variables:
    name: Resolve Manifest Variables
    runs-on: ubuntu-latest
    outputs:
      manifest: outputhello
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Resolve Manifest Variables
        id: resolve
        env:
          AZURE_SUBSCRIPTION_ID: ${{ inputs.manifest }}
          AZURE_RESOURCE_GROUP: ${{ inputs.modifiers }}
          
        run: |
          echo "printing AZURE_SUBSCRIPTION_ID"
          echo $AZURE_SUBSCRIPTION_ID
          echo "printing AZURE_RG"
          echo $AZURE_RESOURCE_GROUP
