name: Install Dependencies

on:
  workflow_call:
    inputs:
      manifest:
        required: true
        type: string
        description: The Path to the Manifest File
      modifiers:
        type: string
        required: false
        default: ""
        description: Semi colon separated key value pairs of environment variables to override


jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    outputs:
      manifest: ${{ steps.resolve.outputs.manifest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        id: resolve
        run: |
          python3 infra/install-dependencies.py

          
