name: CI

on:
  workflow_call:
    inputs:
      skr-client-maa-endpoint:
        description: "Attestation endpoint"
        required: true
        default: ""
        type: choice
        options: 
          - https://dsadsa.com1
          - https://dsadsa.com
      sidecar_registry:
        description: "The registry to get the image from"
        required: true
        default: "http://mcr.microsoft.com"
        type: string
      key-release-image:
        description: "The image of the SKR sidecar to use"
        required: false
        default: "aci/skr:2.7"
        type: string
      kubernetes-version:
        description: "Kubernetes version to use for AKS cluster creation"
        required: true
        default: "1.24.0"
        type: string
      skr-client-akv-endpoint:
        description: "AKV endpoint for key release"
        required: true
        default: ""
        type: string
      skr-kafka-demo-topic:
        description: "Kafka topic"
        required: true
        default: "demo-topic"
        type: string  

  workflow_dispatch:
    inputs:
      skr-client-maa-endpoint:
        description: "Attestation endpoint"
        required: true
        type: choice
        options: 
          - http://mcr.microsoft.com
          - http://confidentialsidecars.azurecr.io
      sidecar_registry:
        description: "The registry to get the image from"
        required: true
        type: choice
        options: 
          - http://mcr.microsoft.com
          - http://confidentialsidecars.azurecr.io
      key-release-image:
        description: "The image of the SKR sidecar to use"
        required: false
        default: "aci/skr:2.7"
        type: string
      kubernetes-version:
        description: "Kubernetes version to use for AKS cluster creation"
        required: true
        default: "1.24.0"
        type: string
      skr-client-akv-endpoint:
        description: "AKV endpoint for key release"
        required: true
        default: ""
        type: string
      skr-kafka-demo-topic:
        description: "Kafka topic"
        required: true
        default: "demo-topic"
        type: string  
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/key_release/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/**
      - infra/**
      - examples/key_release/**
  merge_group:
    branches:
      - main
  schedule:
    - cron: "0 7 * * *"

jobs:
  resolve-image:
    name: Resolve Sidecar Image
    runs-on: ubuntu-latest
    outputs:
      manifest-modifiers: ${{ steps.resolve-image.outputs.manifest-modifiers }}
    steps:
      - name: Define Image to Use
        id: resolve-image
        env:
          SIDECAR_REGISTRY: ${{ inputs.sidecar_registry }}
          KEY_RELEASE_IMAGE: ${{ inputs.key-release-image }}
          TOPIC: ${{vars.TOPIC}}
          SKRCLIENTAKVENDPOINT: ${{vars.SKRCLIENTAKVENDPOINT}}
          SKRCLIENTKID: ${{vars.SKRCLIENTKID}}
          SKRCLIENTMAAENDPOINT: ${{vars.SKRCLIENTMAAENDPOINT}}
        run: |
          echo $SIDECAR_REGISTRY
          echo $TOPIC
          echo $SKRCLIENTAKVENDPOINT
          if [ -z "$SIDECAR_REGISTRY" ]; then
            SIDECAR_REGISTRY="http://mcr.microsoft.com"
          fi
          if [ -z "$KEY_RELEASE_IMAGE" ]; then
            KEY_RELEASE_IMAGE="aci/skr:2.7"
          fi
          echo $SIDECAR_REGISTRY
          echo $KEY_RELEASE_IMAGE
          echo $TOPIC
          echo $SKRCLIENTAKVENDPOINT
          echo $SKRCLIENTMAAENDPOINT
          echo $SKRCLIENTKID
          echo "manifest-modifiers=KEY_RELEASE_IMAGE=$SIDECAR_REGISTRY/$KEY_RELEASE_IMAGE" >> $GITHUB_OUTPUT