name: Push Example Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag to push the image with
        required: true
        type: string
      test-name:
        description: Name of the Test
        required: true
        type: string
      image:
        description: Image to Push (e.g. primary:path/to/Dockerfile)
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        description: Tag to push the image with
        required: true
        type: string
      test-name:
        description: Name of the Test
        required: true
        type: string
      image:
        description: Image to Push (e.g. primary:path/to/Dockerfile)
        required: true
        type: string

jobs:
  push-example-image:
    name: Push Example Image HelloTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: docker.io
          username: stevendongatmsft
          password: tsubaki123

      - name: Get Docker Info
        id: docker-info
        run: |
          echo "repository=HelloTest >> $GITHUB_OUTPUT
          echo "file=ef >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        env:
          DOCKERFILE_CONTEXT: examples
        with:
          context: examples
          file: examples/key_release/Dockerfile.primary
          push: true
          tags: |
            docker.io/stevendongatmsft/hellotest:1
